name: PR Approve with /approve

on:
    pull_request_review:
        types: [submitted]

jobs:
    auto-approve:
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write
        if: github.event.review.body == '/approve' && github.event.review.state == 'commented'
        steps:
            - uses: hmarr/auto-approve-action@v4
